# This is a workflow that applies StackPulse Playbooks and Triggers 

name: StackPulse_Playbooks_and_Triggers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  apply-playbook:
    name: Apply StackPulse Playbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stackpulse/stackpulse-apply-playbook@v0.2
        name: Apply playbook
        with:
          clientId: ${{ secrets.STACKPULSE_CLIENT_ID }}
          clientSecret: ${{ secrets.STACKPULSE_CLIENT_SECRET }}
          yamlFile: ops/get-latest-pods.yml